Lab3
artyom-mankevich/to-do-list-webapp pull request #2
Opened 2022-03-21 19:43 UTC by artyom-mankevich

2022-03-28 10:33 UTC, katetushkan approved these changes

2022-03-28 10:33 UTC, katetushkan commented on index.html
> +            <header class="note-header">
there should be  only one header at the page.

2022-03-28 10:33 UTC, katetushkan commented on templates/main.html
> +        <h4 class="menu-title">Categories</h4>
U can't use h4, if u have no h3, h2, h1 on ur page.

2022-03-28 10:33 UTC, katetushkan commented on templates/main.html
> +                        <img class="note-list__icon"
It should be checkbox

2022-03-28 10:33 UTC, katetushkan commented on templates/signup.html
> +                <input id="emailInput" class="card__input" type="text">
make it type="email" browser will provide u additional validation

2022-03-28 10:33 UTC, katetushkan commented on templates/main.html
> +            <h3 class="side-menu-tags__title">tags:</h3>
U can't use h3 after h4

2022-03-28 10:33 UTC, katetushkan commented on templates/main.html
> +<section class="menu menu_hidden">
should be <nav>

2022-03-28 10:33 UTC, katetushkan commented on templates/main.html
> +    <button class="header__notification-button">
If the main purpose of this is redirecting u to another page with notifications, than it's better to be a link^ not a button.

2022-03-28 10:33 UTC, katetushkan commented on templates/signup.html
> +</html>
<img width="482" alt="Screenshot 2022-03-28 at 12 27 17" src="https://user-images.githubusercontent.com/43992068/160379206-7faa518e-7c88-4c5c-957b-675b938c78b1.png">
small size does not look good(

2022-03-28 10:33 UTC, katetushkan commented on index.html
> +<!DOCTYPE html>
I do mostly like how it looks, so I can give u 9 and recommend u to take a look at the comments I left and take care of them in ur future work if u are OK.

2022-03-28 10:36 UTC, katetushkan commented on index.html
> +<!DOCTYPE html>
U also have a possibility to have a 10 if u'll fix side menu, let me know ur decision.

2022-03-28 10:41 UTC, artyom-mankevich commented on index.html
> +<!DOCTYPE html>
@katetushkan Yeah, I'll fix the side menu and other issues a bit later and notify you in this PR once it is done

2022-03-28 10:48 UTC, artyom-mankevich commented on templates/main.html
> +    <button class="header__notification-button">
There will be a pop-up window with notifications on the button press, so I think button tag fits

2022-03-28 11:30 UTC, katetushkan commented on templates/main.html
> +    <button class="header__notification-button">
okay then

2022-03-29 18:28 UTC, artyom-mankevich commented on index.html
> +<!DOCTYPE html>
@katetushkan fixed the issues you mentioned

2022-04-04 09:08 UTC, katetushkan requested changes
Upgraded

2022-04-04 09:08 UTC, katetushkan approved these changes

2022-04-04 13:44 UTC, merged